rest_mass:
    out_dir: single_hadrons
#     out_type: xmgrace
    out_type: python
#     combine: true
    particles:
        pi:
            files:
                - /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20/single_hadrons/tmin_fit_isotriplet-S0-P000-A1um-PSS0-0_30000A1um-P[SS0]-0T2-25-20_0.agr
                - /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20/single_hadrons/tmin_fit_isotriplet-S0-P000-A1um-PSS0-0_30000A1um-P[SS0]-0T2-25-20_4.agr
            outfilestub: pi0_tmin_all
        N:
            files:
                - /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20/single_hadrons/tmin_fit_isodoublet-S0-P000-G1g-NSS0-0_20000G1g-N[SS0]-0T2-25-20_0.agr
                - /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20/single_hadrons/tmin_fit_isodoublet-S0-P000-G1g-NSS0-0_20000G1g-N[SS0]-0T2-25-20_4.agr
                - /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20/single_hadrons/tmin_fit_isodoublet-S0-P000-G1g-NSS0-0_20000G1g-N[SS0]-0T2-25-15_8.agr
            outfilestub: N0_tmin_all

        
# spectrum_tmins:
#     include_single_exp: True
#     plot_format: 2
#     out_type: python
# #     out_type: xmgrace
#     channels:
#       - name: isodoublet_nonstrange_format1
#         out_dir: isodoublet_npi
#         max_level: 10
#         dir: /latticeQCD/raid3/sarahski/lqcd/D200_R000/isodoublet_nonstrange_bootstrap/.sigmond/plots/spectrum/tmin_plots/isodoublet_nonstrange_colin/rebin20
#         omit:
#           - geometric fit
#           - geometric ratio fit
#           - isodoublet_S0_G1_P1_single_pivot_n4_m4_d8_c50
#           - isodoublet_S0_G1u_P0_single_pivot_n7_m7_d14_c50
#           - isodoublet_S0_G1_P1_single_pivot_n7_m7_d14_c50
#           - isodoublet_S0_G_P2_single_pivot_n7_m7_d14_c50
#           - isodoublet_S0_G_P3_single_pivot_n7_m7_d14_c50
#           - isodoublet_S0_G1_P4_single_pivot_n7_m7_d14_c50
#           - isodoublet_S0_G1_P1_single_pivot_n6_m6_d12_c50
#           - isodoublet_S0_G_P3_single_pivot_n6_m6_d12_c50
#           - isodoublet_S0_G1u_P0_single_pivot_n4_m4_d8_c50
#           - isodoublet_S0_G_P2_single_pivot_n4_m4_d8_c50
#           - isodoublet_S0_G_P3_single_pivot_n4_m4_d8_c50
#           - isodoublet_S0_G1_P4_single_pivot_n4_m4_d8_c50
#           - isodoublet_S0_G1u_P0_single_pivot_n6_m6_d12_c50
#           - isodoublet_S0_G_P2_single_pivot_n6_m6_d12_c50
#           - isodoublet_S0_G1_P4_single_pivot_n6_m6_d12_c50
#           - isodoublet_S0_G1_P1_t_single_pivot_n8_m8_d16_c50
#           - isodoublet_S0_G_P2_t_single_pivot_n8_m8_d16_c50
#           - isodoublet_S0_G_P3_t_single_pivot_n8_m8_d16_c50
#           - isodoublet_S0_G1_P4_t_single_pivot_n8_m8_d16_c50
#           - isodoublet_S0_G1u_P0
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_D_2.pdf
#       - name: isoquartet_nonstrange_fermionic_format3
#         out_dir: isoquartet_npi
#         max_level: 15
#         dir: /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20