# ignore_me: yeah
spectrum tmins:
    include_single_exp: True
    plot_format: 3
    infiles:
#       - name: isodoublet_nonstrange_format1
#         dir: /latticeQCD/raid3/sarahski/lqcd/D200_R000/isodoublet_nonstrange_bootstrap/.sigmond/plots/spectrum/tmin_plots/isodoublet_nonstrange_colin/rebin20
#         omit:
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T10-25-20_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-10R_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-15_4_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ2-G-ROT-3_20p2G-ROT-3T2-25-20R_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T10-25-20_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-10R_8_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-15_4_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_D_3.agr
#           - tmin_fit_isodoublet-S0-PSQ3-G-ROT-3_20p3G-ROT-3T2-25-20R_0_D_3.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T10-25-20_0_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10_8_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-10R_8_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-15_4_D_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_2.pdf
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_D_2.agr
#           - tmin_fit_isodoublet-S0-PSQ4-G1-ROT-2_20p4G1-ROT-2T2-25-20R_0_D_2.pdf
      - name: isoquartet_nonstrange_fermionic_format3
        dir: /latticeQCD/raid3/sarahski/lqcd/D200_R000/isoquartet_nonstrange_fermionic_bootstrap/.sigmond/plots/spectrum/tmin_plots/isoquartet_nonstrange_fermionic_colin/rebin20